language: python
sudo: false

python:
- "3.5"
- "3.6"
- "3.7-dev"

git:
  depth: 2

cache:
  pip: true

branches:
  only:
  - master
  - develop
  - "/^\\d+\\.\\d+\\.\\d+[a]?\\d*$/"

addons:
  apt:
    packages:
    - libopenbabel-dev
    - swig

matrix:
  fast_finish: true

install:
- pip install --upgrade pip setuptools wheel tox tox-travis

script:
- tox -- --cov=structurizr --cov-report xml --cov-report term
- bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: change
    on_failure: change
    on_pull_requests: false
